2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_setup.py:_flush():70] Configure stats pid to 98245
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_setup.py:_flush():70] Loading settings from /Users/grace/.config/wandb/settings
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_setup.py:_flush():70] Loading settings from /Users/grace/Desktop/00OSU/AI 539 NLP/Final Project/CASTLE_1/CASTLE/wandb/settings
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/grace/Desktop/00OSU/AI 539 NLP/Final Project/CASTLE_1/CASTLE/wandb/run-20250612_012726-48m9hcsd/logs/debug.log
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/grace/Desktop/00OSU/AI 539 NLP/Final Project/CASTLE_1/CASTLE/wandb/run-20250612_012726-48m9hcsd/logs/debug-internal.log
2025-06-12 01:27:26,123 INFO    MainThread:98245 [wandb_init.py:init():852] calling init triggers
2025-06-12 01:27:26,124 INFO    MainThread:98245 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'pretrain_epoch': 500, 'finetune_epoch': 200, 'dec_epoch': 6000, 'dims': [313, 228, 114, 20], 'batch_size': 1024, 'corrupt': 0.25, 'n_cluster': 19, 'alpha': 1, 'plot': False, 'pretrain_lr': 0.0001, 'pretrain_momentum': 0.9, 'pretrain_step_size': 100, 'pretrain_gamma': 0.1, 'num_workers': 0, 'train_step_size': 100, 'train_gamma': 0.1, 'train_lr': 0.001, 'train_momentum': 0.9, 'clusteralg': 'louvain', 'reduce_dim': 'pca', 'dec_lr': 0.005, 'dec_step_size': 2000, 'dec_gamma': 0.2, 'stopping_delta': 1e-07, '_wandb': {}}
2025-06-12 01:27:26,124 INFO    MainThread:98245 [wandb_init.py:init():893] starting backend
2025-06-12 01:27:26,124 INFO    MainThread:98245 [wandb_init.py:init():897] sending inform_init request
2025-06-12 01:27:26,143 INFO    MainThread:98245 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-06-12 01:27:26,143 INFO    MainThread:98245 [wandb_init.py:init():907] backend started and connected
2025-06-12 01:27:26,148 INFO    MainThread:98245 [wandb_init.py:init():1005] updated telemetry
2025-06-12 01:27:26,177 INFO    MainThread:98245 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-12 01:27:26,615 WARNING MainThread:98245 [wandb_init.py:init():1681] [no run ID] interrupted
Traceback (most recent call last):
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1055, in init
    result = wait_with_progress(
        run_init_handle,
    ...<2 lines>...
        display_progress=display_init_message,
    )
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ~~~~~~~~~~~~~~~~~~~~~~^
        [handle],
        ^^^^^^^^^
    ...<2 lines>...
        display_progress=display_progress,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )[0]
    ^
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 70, in wait_all_with_progress
    return _wait_handles(handle_list, timeout=progress_after)
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 110, in _wait_handles
    results.append(handle.wait_or(timeout=remaining_timeout))
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/mailbox/mailbox_handle.py", line 122, in wait_or
    return self._fn(self._handle.wait_or(timeout=timeout))
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/mailbox/response_handle.py", line 88, in wait_or
    if not self._event.wait(timeout=timeout):
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/castle/lib/python3.13/threading.py", line 659, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/anaconda3/envs/castle/lib/python3.13/threading.py", line 363, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-06-12 01:27:26,617 WARNING MsgRouterThr:98245 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/anaconda3/envs/castle/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-12 01:27:26,625 INFO    MsgRouterThr:98245 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
